### ISSUE TITLE
Could not find SSID

### ISSUE THREAD

**Issue by Wildhoney** [rauchg/wifi-password#15]
> matilda-pro:~ atimberlake$ wifi-password 
> 
>  … getting password for "HOME-WIFI". 
>  … keychain prompt incoming. 
> ERROR: Could not find SSID "HOME-WIFI"

What happened? Is there a verbose mode?

<kbd>Authenticated via EAP-PEAP (MSCHAPv2)</kbd>

**Comment by KyroChi** [comment]
Not sure for your exact case, but if you are using something like a WPA2 Enterprise network you will not be able to pull and SSID because it uses RADIUS authentication rather than the traditional single password authentication used by WPA2 Personal. For example I cannot get a password for the network at work because, well it doesn't have one.

Is your network `HOME-WIFI` configured with WPA2 or do you login with a password **and** username?

**Comment by Wildhoney** [comment]
I think you're probably right &mdash; I login with both a password and username. WPA2 Enterprise Network is probably the issue here. Thanks.
